#!/bin/bash
##
##   ____ _____ _  __  _____ _                              
##  / ___|_   _| |/ / |_   _| |__   ___ _ __ ___   ___  ___ 
## | |  _  | | | ' /    | | | '_ \ / _ \ '_ ` _ \ / _ \/ __|
## | |_| | | | | . \    | | | | | |  __/ | | | | |  __/\__ \
##  \____| |_| |_|\_\   |_| |_| |_|\___|_| |_| |_|\___||___/
## created by Lyubomir Klaudov (2024)
##
## Set GTK themes, Icons, Cursor and Fonts

THEME = '~/.themes/Nordic-darker-v40'
ICONS = 'Papirus-Dark'
FONT = 'FiraCodeNerdFont-Regular'
CURSOR = '~/.icons/Nordzy-curosr-white'

SCHEMA = 'gsettings set org.gnome.desktop.interface'

apply_theme() {
    ${SCHEMA} gtk-theme "$THEME"
    ${SCHEMA} icon-theme "$ICONS"
    ${SCHEMA} cursor-theme "$FONT"
    ${SCHEMA} font-name "$CURSOR"
}
